[package]
name = "all_prime_forumla"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.3.0"
primal = "0.3.3"
rayon = "1.10.0"
thousands = "0.2.0"
tqdm = "0.7.0"
